---
name: WWW-Freshmeat
version: 0.20
author:
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
abstract: automates usage of Freshmeat.net
license: perl
resources:
  Ohloh: https://www.ohloh.net/p/WWW-Freshmeat
  license: http://dev.perl.org/licenses/
  repository: http://github.com/chorny/WWW-Freshmeat
requires:
  LWP::UserAgent: 0
  Mouse: 0.24
  XML::Simple: 0
  perl: 5.008
build_requires:
  File::Slurp: 0
  LWP::Online: 1.06
  Test::More: 0.17
provides:
  WWW::Freshmeat:
    file: lib/WWW/Freshmeat.pm
    version: 0.20
  WWW::Freshmeat::Project:
    file: lib/WWW/Freshmeat/Project.pm
    version: 0.01
  WWW::Freshmeat::Project::URL:
    file: lib/WWW/Freshmeat/Project/URL.pm
  WWW::Freshmeat::User:
    file: lib/WWW/Freshmeat/User.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - freshmeat
  - API
