--- #YAML:1.0
name:               WWW-Freshmeat
version:            0.11
abstract:           automates searches on Freshmeat.net
author:
    - Alexandr Ciornii <alexchorny@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::TreeBuilder::XPath:  0.09
    LWP::Online:          1.06
    LWP::UserAgent:       0
    perl:                 5.008
    Test::More:           0.17
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
